version: '3'
services:
  web:
    image: buzzword-stack/frontend/base
    build: Frontend/.
    container_name: buzzwordstack_frontend
    restart: always
    ports:
      - "8080:8080"
  api:
    build: Backend/.
    container_name: buzzwordsstack_backend
    restart: always
    ports:
        - "5000:5000"