version: '3'
services:
  web:
    image: buzzword-stack/frontend/base
    build: Frontend/.
    container_name: buzzwordstack_frontend
    restart: always
    ports:
      - "8080:8080"
  api:
    build: Backend/.
    container_name: buzzwordstack_backend
    depends_on:
      - db
    restart: always
    links:
      - db
    ports:
      - "5000:5000"
  db:
    container_name: buzzwordstack_db
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_DB: api_db
      POSTGRES_USER: safeuser
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    expose: 
      - 5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 8000:8080
volumes:
  db-data: